version: '3.7'
services:
  db:
    env_file:
      - .envrc
    image: postgres:latest
    ports: ['5432:5432']

  api:
    env_file:
      - .envrc
    environment:
      - DB_HOST=db
    build:
      context: ./
      dockerfile: ./Dockerfile
    expose: ['3000']
    ports: ['3000:3000']
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules